
CREATE TABLE `customers` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`outlet_id` bigint(20) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`phone` varchar(255) DEFAULT NULL,
`email` varchar(255) DEFAULT NULL,
`address` text DEFAULT NULL,
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `customers_outlet_id_name_index` (`outlet_id`,`name`),
KEY `customers_outlet_id_phone_index` (`outlet_id`,`phone`),
KEY `customers_outlet_id_email_index` (`outlet_id`,`email`),
KEY `customers_outlet_id_is_active_index` (`outlet_id`,`is_active`),
CONSTRAINT `customers_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `discounts` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`outlet_id` bigint(20) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`type` enum('nominal','percent') NOT NULL,
`value` decimal(12,2) NOT NULL,
`note` text DEFAULT NULL,
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `discounts_outlet_id_is_active_index` (`outlet_id`,`is_active`),
CONSTRAINT `discounts_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `order_items` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`order_id` bigint(20) unsigned NOT NULL,
`service_variant_id` bigint(20) unsigned NOT NULL,
`unit` enum('kg','pcs','meter') NOT NULL,
`qty` decimal(10,2) NOT NULL,
`price_per_unit_snapshot` decimal(12,2) NOT NULL,
`line_total` decimal(12,2) NOT NULL,
`note` text DEFAULT NULL,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `order_items_service_variant_id_foreign` (`service_variant_id`),
KEY `order_items_order_id_index` (`order_id`),
CONSTRAINT `order_items_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
CONSTRAINT `order_items_service_variant_id_foreign` FOREIGN KEY (`service_variant_id`) REFERENCES `service_variants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `order_status_histories` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`order_id` bigint(20) unsigned NOT NULL,
`from_status` varchar(255) DEFAULT NULL,
`to_status` varchar(255) NOT NULL,
`by_user_id` bigint(20) unsigned DEFAULT NULL,
`notes` text DEFAULT NULL,
`changed_at` datetime NOT NULL DEFAULT current_timestamp(),
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `order_status_histories_by_user_id_foreign` (`by_user_id`),
KEY `order_status_histories_order_id_index` (`order_id`),
KEY `order_status_histories_order_id_changed_at_index` (`order_id`,`changed_at`),
CONSTRAINT `order_status_histories_by_user_id_foreign` FOREIGN KEY (`by_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
CONSTRAINT `order_status_histories_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `orders` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`outlet_id` bigint(20) unsigned NOT NULL,
`customer_id` bigint(20) unsigned NOT NULL,
`invoice_no` varchar(255) NOT NULL,
`status` enum('ANTRIAN','PROSES','SIAP_DIAMBIL','SELESAI','BATAL') NOT NULL,
`payment_status` enum('UNPAID','PAID') NOT NULL DEFAULT 'UNPAID',
`payment_method_id` bigint(20) unsigned DEFAULT NULL,
`perfume_id` bigint(20) unsigned DEFAULT NULL,
`discount_id` bigint(20) unsigned DEFAULT NULL,
`discount_value_snapshot` decimal(12,2) NOT NULL DEFAULT 0.00,
`subtotal` decimal(12,2) NOT NULL,
`total` decimal(12,2) NOT NULL,
`notes` text DEFAULT NULL,
`checkin_at` datetime NOT NULL DEFAULT current_timestamp(),
`eta_at` datetime DEFAULT NULL,
`finished_at` datetime DEFAULT NULL,
`canceled_at` datetime DEFAULT NULL,
`collected_at` datetime DEFAULT NULL,
`collected_by_user_id` bigint(20) unsigned DEFAULT NULL,
`created_by` bigint(20) unsigned NOT NULL,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `orders_outlet_id_invoice_no_unique` (`outlet_id`,`invoice_no`),
KEY `orders_customer_id_foreign` (`customer_id`),
KEY `orders_payment_method_id_foreign` (`payment_method_id`),
KEY `orders_perfume_id_foreign` (`perfume_id`),
KEY `orders_discount_id_foreign` (`discount_id`),
KEY `orders_collected_by_user_id_foreign` (`collected_by_user_id`),
KEY `orders_created_by_foreign` (`created_by`),
KEY `orders_outlet_id_status_index` (`outlet_id`,`status`),
KEY `orders_outlet_id_created_at_index` (`outlet_id`,`created_at`),
KEY `orders_outlet_id_eta_at_index` (`outlet_id`,`eta_at`),
CONSTRAINT `orders_collected_by_user_id_foreign` FOREIGN KEY (`collected_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
CONSTRAINT `orders_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
CONSTRAINT `orders_customer_id_foreign` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE,
CONSTRAINT `orders_discount_id_foreign` FOREIGN KEY (`discount_id`) REFERENCES `discounts` (`id`) ON DELETE SET NULL,
CONSTRAINT `orders_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE,
CONSTRAINT `orders_payment_method_id_foreign` FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods` (`id`) ON DELETE SET NULL,
CONSTRAINT `orders_perfume_id_foreign` FOREIGN KEY (`perfume_id`) REFERENCES `perfumes` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `outlets` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`owner_user_id` bigint(20) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`logo_path` varchar(255) DEFAULT NULL,
`address` text DEFAULT NULL,
`phone` varchar(20) DEFAULT NULL,
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `outlets_owner_user_id_is_active_index` (`owner_user_id`,`is_active`),
CONSTRAINT `outlets_owner_user_id_foreign` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_methods` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`outlet_id` bigint(20) unsigned NOT NULL,
`category` enum('cash','transfer','e_wallet') NOT NULL,
`name` varchar(255) NOT NULL,
`logo` varchar(255) DEFAULT NULL,
`owner_name` varchar(255) DEFAULT NULL,
`tags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tags`)),
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `payment_methods_outlet_id_category_is_active_index` (`outlet_id`,`category`,`is_active`),
CONSTRAINT `payment_methods_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payments` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`order_id` bigint(20) unsigned NOT NULL,
`method_id` bigint(20) unsigned NOT NULL,
`amount` decimal(12,2) NOT NULL,
`paid_at` datetime NOT NULL,
`ref_no` varchar(255) DEFAULT NULL,
`note` text DEFAULT NULL,
`status` enum('SUCCESS','VOID') NOT NULL DEFAULT 'SUCCESS',
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `payments_order_id_unique` (`order_id`),
KEY `payments_order_id_index` (`order_id`),
KEY `payments_method_id_index` (`method_id`),
KEY `payments_paid_at_index` (`paid_at`),
KEY `payments_status_index` (`status`),
CONSTRAINT `payments_method_id_foreign` FOREIGN KEY (`method_id`) REFERENCES `payment_methods` (`id`) ON DELETE CASCADE,
CONSTRAINT `payments_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `perfumes` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`outlet_id` bigint(20) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`note` text DEFAULT NULL,
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `perfumes_outlet_id_is_active_name_index` (`outlet_id`,`is_active`,`name`),
CONSTRAINT `perfumes_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `service_variants` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`service_id` bigint(20) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`unit` enum('kg','pcs','meter') NOT NULL,
`price_per_unit` decimal(12,2) NOT NULL,
`tat_duration_hours` int(10) unsigned NOT NULL,
`image_path` varchar(255) DEFAULT NULL,
`note` text DEFAULT NULL,
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `service_variants_service_id_is_active_index` (`service_id`,`is_active`),
KEY `service_variants_service_id_unit_index` (`service_id`,`unit`),
CONSTRAINT `service_variants_service_id_foreign` FOREIGN KEY (`service_id`) REFERENCES `services` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `services` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`outlet_id` bigint(20) unsigned NOT NULL,
`name` varchar(255) NOT NULL,
`priority_score` tinyint(4) NOT NULL DEFAULT 50,
`process_steps_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '["cuci","kering","setrika"]' CHECK (json_valid(`process_steps_json`)),
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `services_outlet_id_is_active_index` (`outlet_id`,`is_active`),
KEY `idx_outlet_priority_desc` (`outlet_id`,`priority_score`),
CONSTRAINT `services_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_outlets` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`user_id` bigint(20) unsigned NOT NULL,
`outlet_id` bigint(20) unsigned NOT NULL,
`role` enum('owner','karyawan') NOT NULL,
`permissions_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '{}' CHECK (json_valid(`permissions_json`)),
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `user_outlets_user_id_outlet_id_unique` (`user_id`,`outlet_id`),
KEY `user_outlets_outlet_id_foreign` (`outlet_id`),
KEY `user_outlets_role_is_active_index` (`role`,`is_active`),
CONSTRAINT `user_outlets_outlet_id_foreign` FOREIGN KEY (`outlet_id`) REFERENCES `outlets` (`id`) ON DELETE CASCADE,
CONSTRAINT `user_outlets_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`name` varchar(255) NOT NULL,
`email` varchar(255) DEFAULT NULL,
`phone` varchar(20) DEFAULT NULL,
`email_verified_at` timestamp NULL DEFAULT NULL,
`password` varchar(255) NOT NULL,
`is_active` tinyint(1) NOT NULL DEFAULT 1,
`remember_token` varchar(100) DEFAULT NULL,
`created_at` timestamp NULL DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `users_email_unique` (`email`),
UNIQUE KEY `users_phone_unique` (`phone`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

